quarkus.application.name=fakecap-company

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin

quarkus.grpc.server.use-separate-server=false
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.flyway.migrate-at-start=true

mp.messaging.outgoing.order-processor.connector=smallrye-kafka
mp.messaging.outgoing.order-processor.topic=order

%dev,integration.quarkus.datasource.devservices.port=5432
%dev,integration.quarkus.datasource.devservices.db-name=fakecap

%integration.quarkus.http.port=8090
%integration.kafka.bootstrap.servers=localhost:19092
%integration.quarkus.compose.devservices.project-name=fakecap
%integration.quarkus.compose.devservices.files[0]=../docker-compose.yml
