quarkus.application.name=fakecap-company

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin

quarkus.grpc.server.use-separate-server=false
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

mp.messaging.outgoing.order-processor.connector=smallrye-kafka
mp.messaging.outgoing.order-processor.topic=order

%dev.quarkus.hibernate-orm.sql-load-script=import.sql
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%dev.quarkus.datasource.devservices.port=5432
%dev.quarkus.datasource.devservices.db-name=fakecap
