create table if not exists company
(
    id      bigint not null generated by default as identity primary key,
    address varchar(255) not null,
    country varchar(255) not null,
    email   varchar(255) not null,
    name    varchar(255) not null,
    sector  varchar(255) not null,
    ticker  varchar(255) not null
);

create table if not exists orders
(
    id            varchar(255) not null primary key,
    company_id    bigint not null constraint company_id_fk references company,
    user_id       bigint not null,
    amount        numeric(38, 2) not null,
    error_message varchar(255) null,
    status        varchar(255) not null
);

-- import.sql
INSERT INTO company (name, ticker, address, email, sector, country)
VALUES ('Apple Inc.', 'AAPL', 'Cupertino, CA', 'info@apple.com', 'Technology', 'USA'),
       ('Microsoft Corporation', 'MSFT', 'Redmond, WA', 'info@microsoft.com', 'Technology', 'USA'),
       ('Tesla Inc.', 'TSLA', 'Austin, TX', 'info@tesla.com', 'Automotive', 'USA'),
       ('Amazon.com Inc.', 'AMZN', 'Seattle, WA', 'info@amazon.com', 'E-commerce', 'USA'),
       ('Alphabet Inc.', 'GOOGL', 'Mountain View, CA', 'info@google.com', 'Technology', 'USA'),
       ('Meta Platforms Inc.', 'META', 'Menlo Park, CA', 'info@meta.com', 'Technology', 'USA'),
       ('NVIDIA Corporation', 'NVDA', 'Santa Clara, CA', 'info@nvidia.com', 'Technology', 'USA'),
       ('Netflix Inc.', 'NFLX', 'Los Gatos, CA', 'info@netflix.com', 'Entertainment', 'USA'),
       ('PayPal Holdings Inc.', 'PYPL', 'San Jose, CA', 'info@paypal.com', 'Financial Services', 'USA'),
       ('Adobe Inc.', 'ADBE', 'San Jose, CA', 'info@adobe.com', 'Technology', 'USA');
